from typing import TypedDict, Annotated
from langgraph.graph.message import add_messages


# WHAT:
# Defines the shared state for the entire graph.

# WHY:
# Every node will receive this state, read from it,
# and return updates to it.


class AgentState(TypedDict):
    # Conversation history
    messages: Annotated[list, add_messages]
    
    # annotated is a wraaper to add something extra 
    # to be used by langgraph
    # add_message is a reducer which adds rather replace

    # Current task assigned to the agent
    task: str

    # Outputs generated by different nodes ptrvious to it
    results: list

    # Errors collected during execution of previous nodes
    errors: list

    # Extra information (latency, model, etc.)
    metadata: dict